global.ERROR_ARRAY = "ERROR_ARRAY";
global.ERROR_FORMAT = "ERROR_FORMAT";
global.ERROR_UNDEFINE = "ERROR_UNDEFINE";
global.ERROR_DB = "ERROR_DB";
global.ERROR_DUPLICATE = "ERROR_DUPLICATE";
global.ERROR_AUTHEN = "ERROR_AUTHEN";
 