<?php 
define('ERROR_ARRAY', 'ERROR_ARRAY');
define('ERROR_FORMAT', 'ERROR_FORMAT');
define('ERROR_UNDEFINE', 'ERROR_UNDEFINE');
define('ERROR_DB', 'ERROR_DB');
define('ERROR_DUPLICATE', 'ERROR_DUPLICATE');
define('ERROR_AUTHEN', 'ERROR_AUTHEN');
define('ERROR_PERMISSION', 'ERROR_PERMISSION');

?>